### ISSUE TITLE
Re-add color coding to SimDem2

### ISSUE THREAD

**Issue by SorraTheOrc** [Azure/simdem#102]
In SimDem 1 we had excellent color coding on the console output. This made it much easier to read. We need to re-implement this in SimDem2.

**Comment by lastcoolnameleft** [comment]
This is now implemented as of Commit: https://github.com/Azure/simdem/commit/f96afc5d625ed6d2114c873feacbdbbca3fb8ef1

**Comment by SorraTheOrc** [comment]
Nice :-)

I think this change clearly shows how superior your code is to SimDem1, this is just so much cleaner.
