### ISSUE TITLE
"typing" during demo

### ISSUE THREAD

**Issue by SorraTheOrc** [Azure/simdem#106]
SimDem2 does not simulate typing, as SimDem1 did, in `demo` mode. This is visual "sugar" but makes demo's more interactive as it gives the person doing the demo time to talk to the audience and explain what is happening.

**Comment by lastcoolnameleft** [comment]
Thanks for pointing this out.  I disabled it when I was doing lots of testing, and realized I broke it.  This is fixed now with: https://github.com/Azure/simdem/commit/60cb5a71587746ca85275a4e55a5dbe9311f85a0
