### ISSUE TITLE
Install of SimDem2 fails with latest pip

### ISSUE THREAD

**Issue by SorraTheOrc** [Azure/simdem#111]
# To reproduce

```
$ pip install --upgrade pip
```

Once upgraded:

```
$ pip3 install -v -e .
Traceback (most recent call last):
  File "/usr/bin/pip3", line 9, in <module>
    from pip import main
ImportError: cannot import name 'main'
```

# Problem

According to a [StackOverflow post](https://stackoverflow.com/questions/49836676/python-pip3-cannot-import-name-main-error-after-upgrading-pip):

> pip 10.x adjusts where its internals are situated. The pip3 command you're seeing is one provided by your package maintainer (presumably debian based here?) and is not a file managed by pip.
> You can read more about this on pip's [issue tracker](https://github.com/pypa/pip/issues/5221)

# Workaround
Again, from the above [StackOverflow post](https://stackoverflow.com/questions/49836676/python-pip3-cannot-import-name-main-error-after-upgrading-pip) - you need to downgrade to an earlier version of pip until this is resolved in Debian / Ubuntu.

```
sudo python3 -m pip uninstall pip && sudo apt install python3-pip --reinstall
```

Now run the install again:

```
$ pip3 install -v -e .
```

**Comment by lastcoolnameleft** [comment]
@rgardler Thanks for providing workaround.  I've included it in the main README.md file as a reference:

https://github.com/Azure/simdem/blob/simdem2/README.md
