### ISSUE TITLE
Azure CLI 2.0 commands fail when running in CloudShell

### ISSUE THREAD

**Issue by alexandair** [Azure/simdem#22]
If I try to run an Azure CLI 2.0 command in SimDem, it fails:

```

$ $ echo "hello world"
hello world

$ az vm list -d -o table
/home/aleksandar/simdem/simdem-env/bin/python: Error while finding spec for 'azure.cli' (ImportError: No module named 'azure')

$ az account list
/home/aleksandar/simdem/simdem-env/bin/python: Error while finding spec for 'azure.cli' (ImportError: No module named 'azure')

(simdem-env) aleksandar@Azure:~/bin$
```

**Comment by SorraTheOrc** [comment]
Hmmmm.... I've done some testing of this and it looks like we need to configure the Azure CLI inside the Virtualenv created for SimDem.

I added the virtualenv because Cloudshell would not allow the installation of some packages in the default virtualenv. 

The question is, do we see if we can make Simdem install inside the default env or do we see if we can make Azure CLI work within the SimDem virtual env... This requires some research

In the meantime I recommend running in a Docker container in some other environment. It runs just fine in Docker for Windows.

**Comment by SorraTheOrc** [comment]
@jluk Any thoughts on this issue as it relates to Cloudshell and the AZ CLI.

**Comment by SorraTheOrc** [comment]
closed in error

**Comment by alexandair** [comment]
My primary interest right now is to run Simdem in the Cloud Shell because I want to use it next week at the conference.
I would prefer if both, Azure CLI and Simdev, could run in the default virtualenv. With Simdev virtualenv, we might expect to have some configuration issue with other preinstalled tools in Cloud Shell.

**Comment by SorraTheOrc** [comment]
OK. Well this worked before I added the flask requirement. This requirement is not used in Cloudshell. Therefore we can identify a point in git history that you can use safely.

I'm on my phone right now so can't do it immediately, but I'll find it and tag it early tomorrow.

**Comment by SorraTheOrc** [comment]
I've put a temporary workaround in place for you and will fix this more permanently when I'm able to. Do this to take advantage:

```
git pull
git checkout tags/CloudShell 
pip install -r requirements.txt # don't worry about "already satisfied" this is just a precaution
mkdir -p ~/bin/simdem-dev # probablu already exists from earlier install attempts
cp -r * ~/bin/simdem-dev 
chmod +x ~/bin/simdem-dev/main.py 
ln -s ~/bin/simdem-dev/main.py ~/bin/simdem # will probably complain you already have this from previous installs
```

I hope this unblocks you for your upcoming demo.

**Comment by SorraTheOrc** [comment]
Now that we have a workaround in place we need to fix the larger issue which is recorded in #19

**Comment by jluk** [comment]
I'd have to look deeper into the virtualenv issue when I get a moment, it would seem cleaner to get simdem to work properly within Cloud Shell instead of pairing CLI within simdem's env if possible.

Adding @yugangw-msft in case he has any insight into CLI working within a virtualenv.

**Comment by SorraTheOrc** [comment]
Closing while we refactor SimDem which will change the nature of this issue, and maybe even solve it.
