### ISSUE TITLE
Use README.md instead of script.md

### ISSUE THREAD

**Issue by lastcoolnameleft** [Azure/simdem#5]
For the directory structure, instead of reading the script from script.md, if simdem used README.md, then the Github repo becomes a bit more self-documenting.

This is minor, but would make it so that if someone views the directory, then the README.md is rendered.

**Comment by SorraTheOrc** [comment]
This is a good suggestion, 

The "script.md" is a pointer to the original roots of this project which was about automating demo scripts (it's script as in you say this, you do that) as opposed to executable program scripts. README.md is more natural and I've been thinking of changing this for some time.

Of course we would need to ensure it's backward compatible - that is support both script.md and README.md.

**Comment by lastcoolnameleft** [comment]
Fixed by #11
