### ISSUE TITLE
prereq fails for az cli but it's installed

### ISSUE THREAD

**Issue by rbitia** [Azure/simdem#50]
![image](https://user-images.githubusercontent.com/7662363/29627184-11bf3cbe-87e6-11e7-99e7-38bd5422daba.png)

Simdem is coming back saying it's missing a prereq script for the azure cli installation.
I have azure cli installed anyway but it can't find the readme.md for the azure cli? I checked the path and it should be correct. 

Environment: Bash w/ Ubuntu VM 
My goal: Run ACI tutorial in acs-demos/incubator/aci/create 
both simdem -p and python3 main.py -p gave me the same error

**Comment by SorraTheOrc** [comment]
This is a duplicate of #48 

You can workaround by fixing the path in the MD to work in your specific use case.
