### ISSUE TITLE
test_plan.txt pre-reqs result in incorrect paths

### ISSUE THREAD

**Issue by SorraTheOrc** [Azure/simdem#56]
When running from a test plan we collate all the pre-reqs into a single collection and execute all at once. However, the script_dir is set as the directory of the first script. This results in incorrect paths being calculated for subsequent pre-reqs.

Why are we collating all pre-reqs for tests? It would likely be better to run them one script at a time.

**Comment by rgardler** [comment]
This also results in running prereqs multiple times. For example, [this build](https://circleci.com/gh/Azure/acs-demos/312) has a step that is supposed to delete a K8s cluster, but if you inspect it you will see that it is also creating a cluster because this is a prereq in earlier steps.
