### ISSUE TITLE
Unexpected prompt for $az

### ISSUE THREAD

**Issue by lastcoolnameleft** [Azure/simdem#8]
Running `scripts/run.sh cli /Users/thfalgou/git/azure/acs-demos/incubator/aci demo`

It appears to be a bug with demo.get_current_command() returning an invalid list of variables.  I would offer a PR, but I'm unsure what this would break.

```
$ IP_NUMBER=$(az container show --resource-group $SIMDEM_RESOURCE_GROUP --name $SIMDEM_ACI_INSTANCE_NAME --output tsv --query ipAddress.ip)

Enter a value for $az:

$ echo $IP_NUMBER
```

**Comment by SorraTheOrc** [comment]
I've reproduced this (it's a regression). I don't have time to fix it right now. Should you or someone else have the time the offending code is in https://github.com/Azure/simdem/blob/master/demo.py#L29

Honestly, I thought I'd fixed this, but clearly not.

**Comment by SorraTheOrc** [comment]
Oh wait... the problem is obvious (to someone who knows the code). Fixing now,
