### ISSUE TITLE
SimDem2 Design Consideration: Execution Engine

### ISSUE THREAD

**Issue by lastcoolnameleft** [Azure/simdem#86]
In SimDem1, the Markdown parsing is tightly coupled with command execution.

The proposal is to parse Markdown into a dictionary based [DSL](https://en.wikipedia.org/wiki/Domain-specific_language) that can be passed into a SimDem execution engine.

The structure for this would operate similar to:

Input:
https://raw.githubusercontent.com/Azure/simdem/simdem2/content/complete-features/README.md

Output:
```
{
            'prerequisites': ['prereq.md', 'prereq-2.md'],
            'commands': [
                { 'command': 'echo foo' },
                { 'command': 'echo bar' },
                { 'command': 'echo baz', 'expected_result': 'baz' } ]
        }
```

This has the following advantages:
* Decouples parsing + execution
* Increases cohesion between parser and execution
  * e.g. we can replace [Mistune](https://github.com/lepture/mistune) with [Mistletoe](https://github.com/miyuchina/mistletoe) and not affect the execution engine
* Allows for easier testing and validation of expected commands to run
* In future, SimDem users could pass execution object instead of Markdown if they want to simplify process.

**Comment by SorraTheOrc** [comment]
+1 to this proposal. The whole of SimDem should be (and is being) rewritten. The manual parsing of the Markdown (and most things) are the results of quick hacks that grew with the success of the tool.

The only caveat is that the markdown must be standard markdown. We cannot require documentation writers to learn a syntax that is unique to SimDem. I note there is a proposal (#85) that propose SimDem specific Markdown. I'll address that proposal separately.

**Comment by lastcoolnameleft** [comment]
Yes, this would parse standard markdown; however, we wouldn't be limited to only markdown (e.g. RST, HTML, etc.).  The main benefit is that it would let us separate how we parse and how we execute.  This will make for easier testing and prototyping new features.

The other benefit is that we could implement issue #85 either way and it wouldn't impact anything but the Markdown parser.  (Heck, I'm thinking of implementing both ways and seeing which wins)

**Comment by lastcoolnameleft** [comment]
Closing this since this is now implemented in the core/executor classes.

**Comment by lastcoolnameleft** [comment]
Re-opening because I would like to define the format for the object:

This object covers the following features:
* Prerequisites
* Prerequisite Validation
* Command Execution
* Command Result Validation
* Next Steps

```
{
  'environment_variables': [ 'FOO=foo', 'BAR=bar' ],
  'prerequisites': ['prereq.md', 'prereq-2.md'],
  'prerequisite_validation': { 'cmd': 'echo foo', 'expected_result': 'foo', 'expected_similarity': '.80' },
  'commands': [
    { 'command': 'echo foo' },
    { 'command': 'echo bar' },
    { 'command': 'echo $FOO', 'expected_result': 'foo', 'expected_similarity': .8 } ],
  'next_steps': [
    { 'link': '../step-1.md', 'title': 'Step #1' },
    { 'link': '../step-2.md', 'title': 'Step #2' },
  ]

}
```

@rgardler Anything I'm forgetting?

**Comment by SorraTheOrc** [comment]
I think this covers it all, although I would not call it "Prerequisite Validation" it is certainly used for that, but it is also run as a normal command execution/result at the end of a document run. In this context, it's another test to ensure everything worked correctly. That is, the commands don't change anything, they test that the complete document worked as expected.

So, a typical execution would be:

validation: pass
finished

or

validation: fail
prerequesites
commands
validation: pass

**Comment by lastcoolnameleft** [comment]
@rgardler If I understand correctly, you want to support 2 types of validation:
* Prerequisite validation - If this fails, then the prerequisite has been met and there's no need to run the rest of this file. Proceed as normal.
* Post-execution validation - Determines if the execution of this run has succeeded or not. Similar to an exit-code

Is that accurate?  If so, then I think we should split them up into two separate types of validation.

**Comment by lastcoolnameleft** [comment]
I realize that this structure prevents you from intermixing commands + documentation + prerequisites in a specified order.

For example, if you want to display some text, run a prerequisite, run some commands, then display some text and then run some more commands, we might want something more like this:

```
{
  'environment_variables': [ 'FOO=foo', 'BAR=bar' ],
  'main': [
    { 'type': 'prerequisites':, 'prerequisites': ['prereq.md', 'prereq-2.md'] },
    { 'type': 'validation', 'validation': { 'cmd': 'echo foo', 'expected_result': 'foo', 'expected_similarity': '.80' } }
    { 'type': 'comment', 'comment': 'Now we're going to echo foo' }
    { 'type': 'command', 'command': 'echo foo' },
    { 'type': 'comment', 'comment': 'Now we're going to echo bar' }
    { 'type': 'command', 'command': 'echo bar' },
    { 'type': 'command', 'command': 'echo $FOO', 'expected_result': 'foo', 'expected_similarity': .8 } ],
  'next_steps': [
    { 'link': '../step-1.md', 'title': 'Step #1' },
    { 'link': '../step-2.md', 'title': 'Step #2' },
  ]

}
```

Then it's up to each Parser object to either display/ignore the comments as it sees fit.  This also provides greater flexibility.

**Comment by SorraTheOrc** [comment]
I did not explain the use of the validation section well... there are not two types of validation, only one. To use your summary (with **correction**):

Prerequisite validation - If this **passes**, then the prerequisite has been met and there's no need to run the rest of this file. Proceed as normal.

You post-execution summary **could** be true, but SimDem1 does not treat the validation section differently as your summary suggests. It merely executes the code like any other code block and handles success/failure as with any other test in the document. This does provide an additional set of tests, but it is not used in a special way. That is any failure in the document (regardless of whether it is in the validation section or not) results in an error exit code.

To put it another way. The only difference between the validation section and every other section is that it will be run _first_ if we are processing the doc as a prerequisite, if that run **passes** then the main doc is not run.

In SimDem1 the placement of the validation section is not relevant. SimDem finds the Validation steps and runs them as part of the prerequisite check. When the document content is executed the validation steps are run wherever they appear. The practice of putting it at the end is merely convention (to be clear, I'm not sure if there would be side-effects if it were placed elsewhere, I'm not aware of testing a different order).

In terms of intermixing documentation, when executing Validation sections as a pre-req check SimDem does output the documentation in the prerequisite section (which will explain what the prereq is an why it is needed) but it does not output documentation in the validation section. SimDem1 merely gets the result of the validation, if it passes it outputs a note indicating the pre-req is satisfied, if it fails it notes that it is not satisfied so it's going to run the commands to satisfy it. At this point it runs through the normal execution process, with documentation being output as normal, including in the validation section.

With respect to your most recent proposal how would that support the current structure: https://github.com/Azure/simdem/tree/master/demo_scripts/simdem/syntax#prerequisites You appear to have stripped all opportunitry to have documentation around the prereqs. This relates to the discussion in #85

**Comment by lastcoolnameleft** [comment]
I will chew on your validation points some more.  I think I understand, but will kick the tires around some more to grok it.

Regarding your comment about stripping documentation around pre-reqs, you're absolutely right.  I realized that last night after I posted the commend and realized I need to sleep on the design.  Here's my current proposal:

This markdown:
https://raw.githubusercontent.com/Azure/simdem/simdem2/content/complete-features/context.md

would get parsed into this object:

```
[
            {'type': 'heading', 'level': 1, 'content': 'Prerequisites'},
            {'type': 'prerequisite', 'content': ['prereq.md', 'prereq-2.md']},
            {'type': 'heading', 'level': 1, 'content': 'Do stuff here'},
            {'type': 'text',
             'content': 'We want to execute this because the code type is shell'},
            {'type': 'commands', 'content': ['echo foo', 'echo bar']},
            {'type': 'heading', 'level': 1, 'content': 'Do more stuff here'},
            {'type': 'commands', 'content': ['echo baz']},
            {'type': 'heading', 'level': 1, 'content': 'Results'},
            {'type': 'text',
             'content': "The only thing that makes it a result is the code type is result. " +
                        "We assume the result is for the last command of the last code block"},
            {'type': 'result', 'content': 'baz'},
            {'type': 'heading', 'level': 1, 'content': 'Next Steps'},
            {'type': 'text',
             'content': 'The list inside this block are steps that could be followed ' +
                        'when performing an interactive tutorial'},
        ]
```

This is more natural to the way SimDem processes documents.  It converts a context-driven document into iterative steps that can be executed (or displayed).

This allows us to implement different shells (bash/powershell) and/or processors (automated-test which ignore all headings/text, Demo which display headers/text, etc.).

**Comment by SorraTheOrc** [comment]
Right, but the markdown you are using to design this is not representative of the complete feature set in SimDem1. Specifically, it does not accommodate documentation around prereqs. Consequently your example output does not demonstrate how the documentation comments would be encapsulated and, further, it looks to me like they cannot since you are concatenating the prereqs into a single object with type ' prerequisite' which does not appear to have a place for documentation.

It is better to work from the documentation of SimDem1 (as linked in my previous comment) or, if you want to keep it more concise use the [test documents](https://github.com/Azure/simdem/tree/master/demo_scripts/test/prerequisites). Both of these have natural language documentation in the pre-reqs section. How would that be represented in this form?

**Comment by lastcoolnameleft** [comment]
Good catch.  You found a bug (hopefully, not a feature).  My latest code should allow for natural language documentation in pre-reqs.

I've created a directory with the full feature-set that should maintain SimDem1 backward compatibility.  Let me know if I'm missing anything.

https://github.com/Azure/simdem/tree/simdem2/content/simdem1

It's now easy to see exactly what SimDem would produce:

I've updated it to now look like this:
```
•100% ➜ ./main.py -m debug  content/simdem1/README.md
[{'content': 'Prerequisites', 'level': 1, 'type': 'heading'},
 {'content': 'This is the prerequisite section.  SimDem looks for a set of '
             'links to extract and run through first',
  'type': 'text'},
 {'content': ' * prereq-ignored', 'type': 'text'},
 {'content': ['content/simdem1/prereq-ignored.md'], 'type': 'prerequisites'},
 {'content': "They don't even need to be in the same list", 'type': 'text'},
 {'content': ' * prereq-processed', 'type': 'text'},
 {'content': ['content/simdem1/prereq-processed.md'], 'type': 'prerequisites'},
 {'content': 'By this point, the prerequisites have either run or have passed '
             'their validation',
  'type': 'text'},
 {'content': 'Did our prerequisites run?', 'level': 1, 'type': 'heading'},
 {'content': ['echo prereq_ignored = $prereq_ignored',
              'echo prereq_processed = $prereq_processed'],
  'type': 'commands'},
 {'content': 'Do stuff here', 'level': 1, 'type': 'heading'},
 {'content': 'We want to execute this because the code type is shell',
  'type': 'text'},
 {'content': ['echo foo', 'var=bar'], 'type': 'commands'},
 {'content': 'Do more stuff here', 'level': 1, 'type': 'heading'},
 {'content': 'We assume the result is for the last command of the last code '
             'block',
  'type': 'text'},
 {'content': ['echo baz', 'echo $var'], 'type': 'commands'},
 {'content': 'bar', 'type': 'result'},
 {'content': 'Next Steps', 'level': 1, 'type': 'heading'},
 {'content': 'The list inside this block are steps that could be followed when '
             'performing an interactive tutorial',
  'type': 'text'}]
```

**Here's an example of SimDem running that exact file**

Everything you see below is what you'd expect to see SimDem display when displaying output, with the exception of any lines that begin and end with '***'.  Those are for easier understanding of SimDem Internals.

If you're bold, you should be able to run the command and test it yourself.

```
•100% ➜ ./main.py  content/simdem1/README.md
*** Processing content/simdem1/README.md ***
# Prerequisites

This is the prerequisite section.  SimDem looks for a set of links to extract and run through first

 * prereq-ignored

*** Processing content/simdem1/prereq-ignored.md ***
# WE ARE IN prereq-ignored.md

This file is designed to have the validation pass.  This means that we should stop executing this document after the results section

# Validation

This is a validation section.  If this validation section passes, we stop processing this file.  The command below should be the last text displayed

$ echo prereq_validation_pass
prereq_validation_pass

***VALIDATION PASSED***
*** Completed Processing content/simdem1/prereq-ignored.md ***
They don't even need to be in the same list

 * prereq-processed

*** Processing content/simdem1/prereq-processed.md ***
# WE ARE IN prereq-processed.md

This file is designed to have the validation fail.  This means that we should completely execute this file

# Validation

This is a validation section.  If this validation section passes, we stop processing this file

$ echo prereq_validation_fail
prereq_validation_fail

***VALIDATION FAILED***
# Main area

This should be run since the validation for the prereq has failed

$ echo YOU SHOULD SEE THIS
YOU SHOULD SEE THIS

# Set a variable that passes through

$ prereq_processed=true

*** Completed Processing content/simdem1/prereq-processed.md ***
By this point, the prerequisites have either run or have passed their validation

# Did our prerequisites run?

$ echo prereq_ignored = $prereq_ignored
prereq_ignored =
$ echo prereq_processed = $prereq_processed
prereq_processed = true

# Do stuff here

We want to execute this because the code type is shell

$ echo foo
foo
$ var=bar

# Do more stuff here

We assume the result is for the last command of the last code block

$ echo baz
baz
$ echo $var
bar

***VALIDATION PASSED***
# Next Steps

The list inside this block are steps that could be followed when performing an interactive tutorial

*** Completed Processing content/simdem1/README.md ***
```

**Comment by lastcoolnameleft** [comment]
This has been implemented.  An example parser that converts MD to a SEO is here:
https://github.com/Azure/simdem/blob/simdem2/simdem/parser/simdem1.py
