### ISSUE TITLE
SimDem 2 Design: Duplicate functionality for Results/Validation

### ISSUE THREAD

**Issue by lastcoolnameleft** [Azure/simdem#88]
Looking at the functionality of SimDem v1, the results and validation functionality are extremely similar.

Going forward, I'd like to split this functionality as such:

Create a function which compares the result of the previously run command as per the options provided (e.g. expected_simularity=.80; exit_code=0; etc.)

Create SimDem Execution Object key/value for applying the comparison function to either a command or to a prerequisite.

I expect the SimDem Execution Object would look like this:

For Prerequisite:
```
{ 'prerequisite_validation': { 'cmd': 'echo foo', 'expected_result': 'foo', 'expected_similarity': '.80' } ... }
```

For command results:
```
{ 'commands': [
    { 'command': 'echo baz', 'expected_result': 'baz', 'expected_exit_code': 0 }
  ]
} 
```

Thoughts?

**Comment by SorraTheOrc** [comment]
As noted in #86 validation is not just for checking whether a prerequisite should run, it is also for checking that a run was successful. It's somewhat like an integration test where the command results are unit tests.

So, a typical execution would be:
validation: pass
finished

or

validation: fail
prerequesites
commands
validation: pass

For this reason I wouldn't call it prerequisite_validation, but I have no objection to the idea of separating it conceptually from a command/result pair.

**Comment by lastcoolnameleft** [comment]
This feature has been implemented in SimDem2 and is in the ModeCommon class.
