### ISSUE TITLE
SimDem 2 Feature:  Break out UI into separate class

### ISSUE THREAD

**Issue by lastcoolnameleft** [Azure/simdem#93]
Currently SimDem 2 prints to screen, but to support other input/outputs (such as terminal colors, possibly NoVNC) we should separate out the UI into a different class.

**Comment by SorraTheOrc** [comment]
You might want to take a look at how I started to do this in SimDem1. If you run with --webgui switch it starts a web server with two separate output sections, one with the notes, one with the console. By breaking the console into a separate browser window it is possible to have a "speaker view" and an "audience" view of the output.

This is how I do my live sessions with SimDem, a way to reproduce the same result would be great.

**Comment by lastcoolnameleft** [comment]
I finally took some time to experiment with the novnc mode and I believe that for SimDem, it breaks the UNIX philosophy of "do one thing and do it well".  

I'm ok with having a way to stand up a linux desktop environment; however, I believe that it should be a separate repo and that SimDem should remain focused on solely as a CLI demo, tutorial, test tool. 

Similarly, I would like to not introduce any Azure specific references (e.g. azure CLI, Azure Volume, etc.)  

Instead I believe SimDem should enable users to customize their own run-time environment instead of baking that into the core.  This would also show flexibility and extensibility of the tool.

For my issue, perhaps "UI" is a misnomer, but I would like a way to have a "color-coded" or "normal text".  I've experienced issues with the ANSI/VT100 commands caused unexpected issues. 

Thoughts?

On a side note, I noticed that --webui (and --webgui) are not working as the documentation states.  (Irony!)
```
➜  simdem git:(master) ✗ docker run -it -p 8080:8080 rgardler/simdem --webui true

Usage: simdem [tutorial|demo|learn|test|script] <options> DEMO_NAME

simdem: error: no such option: --webui
```

**Comment by SorraTheOrc** [comment]
+1 (note I've never said anything about the novnc mode in the context of Simdem2 (which by the way is a bad name, SimDem 1 had never been made).

Novnc was  created to some a particular problem and had mostly been replaced by webui, which I believe does fit the design goals of SimDem (is simply an HTML view on the application). 

I'm in a phone, so can't test it right now, but it should work, and has been used by me but not for a good few months. I'll look into it.

**Comment by lastcoolnameleft** [comment]
Implemented and refactored existing classes to use BasicUI.  This can be expanded to include other UI classes now.

https://github.com/Azure/simdem/blob/simdem2/simdem/ui/basic.py
